FROM golang:1.15-alpine AS build_base

RUN apk add --no-cache git

WORKDIR /cloud

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o ./bin/cloud ./cloud/cmd/

FROM alpine:3.9
RUN apk add ca-certificates

COPY --from=build_base /cloud/bin/cloud /app/cloud

EXPOSE 7890
EXPOSE 8900

CMD ["/app/cloud"]

