FROM golang:1.15-alpine AS build_base

RUN apk add --no-cache git

WORKDIR /agent

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o ./bin/agent ./agent/cmd/

FROM alpine:3.9

COPY --from=build_base /agent/bin/agent /app/agent

EXPOSE 7000

CMD ["/app/agent"]

